[platformio]
default_envs = esp32s3-zero-m

[env:esp32s3-zero-m]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
board = waveshare_esp32_s3_zero_m
monitor_speed = 115200
